### DISCUSSION TITLE
Authenticating to AWS EKS Cluster

### DISCUSSION THREAD

**Discussion by jseiser** [runatlantis/helm-charts#257] [General] [answered]
We are having problem getting Atlantis to be able to run TF commands against the EKS cluster.

```
❯ kubectl get configmap -n kube-system aws-auth -o yaml
apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws-us-gov:iam::xxx:role/role-atlantis-prod"
      "username": "atlantis-admin"
```

Pod is deployed with a serviceAccount

```
  serviceAccount: atlantis-sa
```

That Service account is wired up for IRSA

```
❯ kubectl get serviceaccount atlantis-sa -n atlantis -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::xxx:role/role-prod-atlantis
```

The pod has all the env vars I would expect

```
_apt@atlantis-0:/$ printenv | grep AWS
AWS_DEFAULT_REGION=us-gov-west-1
AWS_REGION=us-gov-west-1
AWS_ROLE_ARN=arn:aws-us-gov:iam::xxx:role/role-prod-atlantis
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
```

it works at a basic level

```
atlantis@atlantis-0:~/.aws$ aws s3 ls
2022-06-30 15:46:21 cloudtrail-global-xxxxx
2022-09-26 15:33:38 xxx-qa-xxxx
```

Our Gitlab instance is deployed the same way, and it works. So I dont think its an issue on the aws/auth side

Our dockerfile

```
FROM ghcr.io/runatlantis/atlantis:v0.22.3-debian

RUN sh -c 'curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm -rf ./aws awscliv2.zip && aws --version'
```

When i hop into the pod, i can run aws CLI, but generating a token fails

```
_apt@atlantis-0:/$ aws --version
aws-cli/2.9.17 Python/3.9.11 Linux/5.4.226-129.415.amzn2.x86_64 exe/x86_64.debian.11 prompt/off
_apt@atlantis-0:/$ aws eks get-token --cluster-name eks-cluster-prod

[Errno 13] Permission denied: '/nonexistent'
```

Makes sense, since this chart runs you as a user, which doesnt have a home dir.  Im not sure why that is, but its expected.

So i tried to run as the atlantis user, and that lets you generate a token

```
statefulSet:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    fsGroupChangePolicy: "OnRootMismatch"
```

```
atlantis@atlantis-0:/$ whoami
atlantis
atlantis@atlantis-0:/$ aws eks get-token --cluster-name eks-cluster-prod
{"kind": "ExecCredential", "apiVersion": "client.authentication.k8s.io/v1beta1", "spec": {}, "status": {"expirationTimestamp": "2023-01-25T21:51:43Z", "token": "k8s-aws-v1.aHR0cHM6Lyxxxxxxx"}}
```

but no matter what, I get.  Which i really doubt, since we have already confirmed we have a SA, that has access to AWS s3, and that it exists in the aws-auth configmap.

```
╷
│ Error: Unauthorized
│ 
│   with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
│   on .terraform/modules/eks/[main.tf](http://main.tf/) line 527, in resource "kubernetes_config_map_v1_data" "aws_auth":
│  527: resource "kubernetes_config_map_v1_data" "aws_auth" {
│ 
╵```
