### DISCUSSION TITLE
How to allowlist Bitbucket's IP addresses

### DISCUSSION THREAD

**Discussion by gojanpaolo** [runatlantis/helm-charts#402] [Q&A] [answered]
Hi! The installation guide says to
> allowlist Bitbucket's IP addresses

But how do we actually do this?

I tried setting this in the values.yaml to see that atlantis would stop working. But atlantis was still working. Meaning this is not the place to set the ip addresses

```
service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 1.2.3.4/32
```
