### ISSUE TITLE
unable to create dir "/atlantis-data/bin": mkdir /atlantis-data/bin: permission denied

### ISSUE THREAD

**Issue by nokernel** [runatlantis/helm-charts#149]
Using atlantis helm chart version 4.0.1.

Getting this when scaling up the statefulset replicas from 1 to 2, and also when doing a fresh install on a new namespace.

**Comment by akhan23wgu** [comment]
Not sure what's changed in the new helm chart exactly, but if you have a PVC configured for that zone, it'll use the root path.

From there, you'll need to set the proper security context (example below). I was able to get past the error, but now I am getting `Error: initializing server: initializing terraform: writing generated .terraformrc file with TFE token to /.terraformrc: open /.terraformrc: permission denied`, even though folders were created on pod creation and my user (99) has full permissions to write to the designated directory.

```    
securityContext:
  fsGroup: 100
  runAsUser: 99
  fsGroupChangePolicy: "OnRootMismatch"
  priorityClassName: ""
```

**Comment by nitrocode** [comment]
That's bizarre. The volume claim template looks exactly the same.

https://github.com/runatlantis/helm-charts/blob/bc9db325f8f023a282fabe03de6a5fb9b969ac7a/charts/atlantis/templates/statefulset.yaml#L520-L548

Values

https://github.com/runatlantis/helm-charts/blob/bc9db325f8f023a282fabe03de6a5fb9b969ac7a/charts/atlantis/values.yaml#L271-L283

Is this still an issue with the latest helm chart?

Could you show the helm template command diff between supplying the deprecated input and omitting it? Perhaps that will bubble up the issue here.

**Comment by GMartinez-Sisti** [comment]
Is this still happening?

**Comment by creeram** [comment]
I'm getting the same issue while deploying with the helm chart version 5.5.0. @GMartinez-Sisti .

**Comment by GMartinez-Sisti** [comment]
> I'm getting the same issue while deploying with the helm chart version 5.5.0. @GMartinez-Sisti .

Hi @creeram, please share your values file (redacted) so we can test it please.

**Comment by creeram** [comment]
```
atlantisUrl: "**********"
orgAllowlist: github.com/*****/*
gitconfigReadOnly: true
extraArgs:
   - --disable-autoplan

image:
  repository: ghcr.io/runatlantis/atlantis
  tag: "v0.29.0"
  pullPolicy: Always
repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: [approved, mergeable]
    allowed_overrides: [workflow,plan_requirements]
    allow_custom_workflows: true
  workflows:
    terragrunt:
      plan:
        steps: [plan]
      apply:
        steps: [apply]
  metrics:
    prometheus:
      endpoint: /metrics
      
githubApp:
  id: *****
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    
    *********************************
    -----END RSA PRIVATE KEY-----

  secret: **********

volumeClaim:
  enabled: true
  dataStorage: 20Gi
  storageClassName: ""
  accessModes: ["ReadWriteMany"]


replicaCount: 3

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "**********"

service:
  type: ClusterIP
  port: 80
  portName: atlantis
  targetPort: 4141

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  pathType: ImplementationSpecific
  host: "*********"



environment:
  TERRAGRUNT_TFPATH: /plugins/terraform


initConfig:
  enabled: true
  image: alpine:latest
  imagePullPolicy: IfNotPresent
  sharedDir: /plugins
  sharedDirReadOnly: true
  workDir: /tmp
  sizeLimit: 200Mi
  script: |
    #!/bin/sh
    set -eoux pipefail

    # example for terragrunt
    TG_VERSION="v0.63.4"
    TG_SHA256_SUM="b3ab5ef5176bee485052de29afe5fbeb9f2fff8a8d6f1c83e7db49776a47a850"
    TG_FILE="${INIT_SHARED_DIR}/terragrunt"
    wget https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64 -O "${TG_FILE}"
    echo "${TG_SHA256_SUM}  ${TG_FILE}" | sha256sum -c
    chmod 755 "${TG_FILE}"
    terragrunt -v

    # Terraform
    TF_VERSION="1.5.7"
    TF_FILE="${INIT_SHARED_DIR}/terraform"
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip terraform_${TF_VERSION}_linux_amd64.zip
    mv terraform ${INIT_SHARED_DIR}
    chmod 755 "${TF_FILE}"
    terraform -v

lockingDbType: "redis"
redis:
  host: ********
  port: 6379

redisSecretName: "****"

```

This is the values file and I'm trying to use ReadWriteMany PVC so that 3 replicas can use the same volume. @GMartinez-Sisti
