### ISSUE TITLE
ingress doesn't forward any path except `/`

### ISSUE THREAD

**Issue by gurpalw** [runatlantis/helm-charts#166]
latest `4.0.5` chart.

```
ingress:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-redacted, sg-redacted
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
  enabled: true
  host: atlantis.dev.com #redacted real value
  ingressClassName: alb
```

Using the above values in my `values.yaml` results in only the `atlantis.dev.com/` path being resolved by the alb. `atlantis.dev.com/events` and `atlantis.dev.com/status` all fail with 404 not found.

see below image of the resulting alb listener rule in aws when using the above values.
  
![image](https://user-images.githubusercontent.com/37112979/179115732-2a14d5bb-f910-4a1e-be31-7605eda2cefa.png)

Instead i had to add the below values in addition to get it to forward all paths after the slash.

```
ingress:
  path: /*
  pathType: ImplementationSpecific
```
 
the alb ingressClassName is referring to my deployment of the aws load balancer controller chart version 1.4.1
