### ISSUE TITLE
how to filter webhook by branch 

### ISSUE THREAD

**Issue by grglzrv** [runatlantis/helm-charts#192]
Hello,

I have one repo with two branches - master and staging, two atlantis server installed on stage and prod k8s cluster. When i create PR from custom branch to master i receive atlantis updates for both of them - stage and prod

Could you please help me how to receive update only to PROD if the PR is opened to master 

my repo config on prod
```
      repos:
      - id: bitbucket.org:xxxxx/repo-name
        branch: master
        workflow: prod
        apply_requirements: [approved, mergeable]
        allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
        allowed_workflows: [prod]
        allow_custom_workflows: false
      workflows:
        prod:
          plan:
            steps:
            - run: echo "Terraform Init and Plan"
            - init:
                extra_args: ["-lock=false"]
            - plan:
                extra_args: ["-lock=false"]
          apply:
            steps:
            - run: echo "Terraform Apply"
            - apply:
                extra_args: ["-lock=false"]
```
prod
atlantis.yaml
```
version: 3
automerge: true
delete_source_branch_on_merge: true
parallel_plan: true
parallel_apply: true
projects:
- name: ec2
  dir: ./../terraform
  workspace: prod
  terraform_version: v1.1.1
  delete_source_branch_on_merge: true
  autoplan:
    when_modified: ["*.tf", "*.tfvars"]
    enabled: true
  apply_requirements: [mergeable, approved]
  workflow: prod
workflows:
  prod:
    plan:
      steps:
      - run: echo "In Terraform Init and Plan"
      - init:
          extra_args: ["-lock=false"]
      - plan:
          extra_args: ["-lock=false"]
    apply:
      steps:
      - run: echo "In Terraform Apply"
      - apply:
          extra_args: ["-lock=false"]
```

Stage - repo config

```
      repos:
      - id: bitbucket.org:xxxxxx/repo-name
        branch: staging
        workflow: myworkflow
        apply_requirements: [approved, mergeable]
        allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
        allowed_workflows: [myworkflow]
        allow_custom_workflows: true
      workflows:
        myworkflow:
          plan:
            steps:
            - run: echo "Terraform Init and Plan"
            - init:
                extra_args: ["-lock=false"]
            - plan:
                extra_args: ["-lock=false"]
          apply:
            steps:
            - run: echo "Terraform Apply"
            - apply:
                extra_args: ["-lock=false"]
```
atlantis.yaml
```
version: 3
automerge: true
delete_source_branch_on_merge: true
parallel_plan: true
parallel_apply: true
projects:
- name: eks node group tokyo stage
  dir: ./../terraform
  workspace: staging
  terraform_version: v1.1.1
  delete_source_branch_on_merge: true
  autoplan:
    when_modified: ["*.tf", "*.tfvars"]
    enabled: true
  apply_requirements: [mergeable, approved]
  workflow: myworkflow
workflows:
  myworkflow:
    plan:
      steps:
      - run: echo "In Terraform Init and Plan"
      - init:
          extra_args: ["-lock=false"]
      - plan:
          extra_args: ["-lock=false"]
    apply:
      steps:
      - run: echo "In Terraform Apply"
      - apply:
          extra_args: ["-lock=false"]
```

**Comment by grglzrv** [comment]
i have just tried with simple repo.yaml config
```
      repos:
      - id: /.*/
        branch: /(^master$)/
        apply_requirements: [approved, mergeable]
        delete_source_branch_on_merge: true
```
and
```
 branch: /(master|staging)/ 
 
 and 
 
 branch: /^master$/ 
```

atlantis version v0.19.8
