### ISSUE TITLE
Ingress manifest breaks yaml spec when `ingress.apiVersion` is set to `networking.k8s.io/v1` with `ingress.hosts`

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [runatlantis/helm-charts#216]
This issue impacts v4.1.3, v4.2.0, v4.2.1

With the [last ingress change](https://github.com/runatlantis/helm-charts/commit/d2ff350c01bb9e645a75b01770fc76241e66ac30#diff-a64350cdd469435fbac7fd5166d59fa54df7be8c58a853775a8d52f354e5a97fR82), when setting values ingress.apiVersion is set to networking.k8s.io/v1
The ingress render, puts in the same line backend and service ( due to the "{{- if eq $apiVersion "networking.k8s.io/v1" -}}")
```
     http:
        paths:
          - path: /
            backend:service:
                name: atlantis
                port:
                  number: 80
``

**Comment by nitrocode** [comment]
Could you show your inputs, what the yaml returns, and what you expect?

**Comment by marcportabellaclotet-mt** [comment]
helm template atlantis runatlantis/atlantis --version=4.2.1
values.yaml
```
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  hosts:
    - host: atlantis.example
      service: atlantis
      paths: ["/"]
```
Renderer ingress manifest
```
# Source: atlantis/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis
  labels:
    app: atlantis
    chart: atlantis-4.2.1
    release: atlantis
    heritage: Helm
spec:
  rules:
    -
      host: "atlantis.example"
      http:
        paths:
          - path: /
            backend:service:
                name: atlantis
                port:
                  number: 80
            pathType: ImplementationSpecific

```
changing {{- if eq $apiVersion "networking.k8s.io/v1" -}} to {{- if eq $apiVersion "networking.k8s.io/v1" }} may solve the issue?

**Comment by nitrocode** [comment]
@marcportabellaclotet-mt can you submit a PR for now and we will review?

**Comment by nitrocode** [comment]
I'm not quite sure on the issue. Are you saying the issue is due to the 2 extra spaces prefixed to name, port, and number?

**Comment by nitrocode** [comment]
Oh I see what you're saying. I updated the formatting of the code and it's more clear to me. Yes, please test out that change locally and verify that the service key is put on the following line. Good catch.

**Comment by marcportabellaclotet-mt** [comment]
Templating the chart with the same values.yaml with [this](https://github.com/runatlantis/helm-charts/pull/217) change:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlantis
  labels:
    app: atlantis
    chart: atlantis-4.2.2
    release: atlantis
    heritage: Helm
spec:
  rules:
    -
      host: "atlantis.example"
      http:
        paths:
          - path: /
            backend:
              service:
                name: atlantis
                port:
                  number: 80
            pathType: ImplementationSpecific

```
And ingress is correctly created:
```
NAME            CLASS    HOSTS                  ADDRESS           PORTS     AGE
atlantis        public   atlantis.example                         80        4s
```
