### ISSUE TITLE
Support EFS CSI by changing volume claim

### ISSUE THREAD

**Issue by cep21** [runatlantis/helm-charts#22]
Hi,

EFS is great for atlantis since it's not locked to a single AZ.  The future of EFS kubernetes is https://github.com/kubernetes-sigs/aws-efs-csi-driver.  There's no way (I know of) to use volumeclaimtemplates (which this helm chart uses) with the CSI spec.  There are details here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/42

Rather than a storageclass inside the volumeclaimtemplates, can we use our own PersistentVolume (where we can configure a volumeHandle) ?

**Comment by nilsSure** [comment]
+1

**Comment by nitrocode** [comment]
Looks like you can provide your own StorageClass using name `efs-atlantis`

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-atlantis
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: <EFS ID>
  directoryPerms: "777"
```

Then set the volume claim to the new storage class

```yaml
volumeClaim:
  storageClassName: efs-atlantis
```

https://github.com/runatlantis/helm-charts/blob/bc9db325f8f023a282fabe03de6a5fb9b969ac7a/charts/atlantis/templates/statefulset.yaml#L540-L542

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/541#issuecomment-1027226852
