### ISSUE TITLE
Error: field repo_config_file not found in type raw.Repo

### ISSUE THREAD

**Issue by noordeen03** [runatlantis/helm-charts#237]
We are setting up 2 Atlantis servers pointing to a single repository as per the following doc,
[](https://www.runatlantis.io/docs/server-side-repo-config.html#multiple-atlantis-servers-handle-the-same-repository)

And our repos.yaml specification will be as follows:

```
 repoConfig: |
    ---
    repos:
    - id: /.*/
      repo_config_file: "atlantis-dev.yaml"
```
And we are getting following error and the POD is not running : 
    
`Error: initializing server: parsing /etc/atlantis/repos.yaml file: yaml: unmarshal errors:
  line 4: field repo_config_file not found in type raw.Repo
`

Can you help us resolve this issue ?
