### ISSUE TITLE
lifecycle hook to wait until all terraform processes are completed

### ISSUE THREAD

**Issue by nitrocode** [runatlantis/helm-charts#258]
Lifecycle hooks are supported but it would be nice to add

- either a default lifecycle to prevent terraform from being killed in the middle of an apply or plan
    - otherwise we could have resources created and the information is not saved into the tfstate
    - otherwise we could have stale dynamodb locks
- or document the lifecycle hook to be optionally added

cc: @Balsir since you added the lifecycle feature to this repo, have you figured out a good `preStop` lifecycle ?

References
- https://github.com/runatlantis/helm-charts/pull/220
- https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by nitrocode** [comment]
Yes, graceful termination should be implemented in the server. I was thinking this lifecycle method could be a nice workaround for now. :smile:

**Comment by GenPage** [comment]
@nitrocode Should we close this issue and create one on the Atlantis repo?

**Comment by nitrocode** [comment]
I think we can have both issues. One here for lifecycle method and one for graceful termination in the server.

**Comment by mubarak-j** [comment]
currently, this helm chart supports pod lifecycle hooks: https://github.com/runatlantis/helm-charts/blob/4afd2a82b1fcc31026c4c392e6984895818b3e62/charts/atlantis/values.yaml#L489-L490

**Comment by mubarak-j** [comment]
This is what I came up with, let me know if seems okay and I will create a PR.

```yaml
statefulSet:
  terminationGracePeriodSeconds: 180

lifecycle:
  preStop:
    exec:
      command:
        - /bin/bash
        - -c
        - while [ "$(pgrep -f terraform)" ]; do sleep 1; done
```

**Comment by keviiin38** [comment]
I slightly adapted @mubarak-j's version in order to support Terraform, OpenTofu and Terragrunt

```yaml
terminationGracePeriodSeconds: 300

lifecycle:
  preStop:
    exec:
      command:
        - /bin/sh
        - -c
        - while pgrep -x "terraform|tofu|terragrunt" > /dev/null; do sleep 1; done
```
