### ISSUE TITLE
atlantis unable to install helm chart: User "system:serviceaccount:atlantis:atlantis" cannot get resource "serviceaccounts" in API group "" in the namespace "xxx"

### ISSUE THREAD

**Issue by papanito** [runatlantis/helm-charts#260]
When I try to install a helm chart with atlantis, I get this error

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource ServiceAccount "nfs-subdir-external-provisioner" in namespace "xxxx": serviceaccounts "nfs-subdir-external-provisioner" is forbidden: User "system:serviceaccount:atlantis:atlantis" cannot get resource "serviceaccounts" in API group "" in the namespace "xxxx"
```

I can install the same helm chart manually.
In our other atlantis instance, the same installation works fine

## Details

We have 2 atlantis installation, one in non-prd one in prd.
We use tokens for the terraform providers, the user has admin permissions (same on both clusters)

```
...
    environmentSecrets:
      - name: TF_VAR_RANCHER_NOP_TOKEN
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_NOP_TOKEN
      - name: TF_VAR_RANCHER_NOP_SECRET
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_NOP_SECRET
      - name: TF_VAR_RANCHER_NOP_API_URL
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_NOP_API_URL
      - name: TF_VAR_RANCHER_PRD_TOKEN
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_PRD_TOKEN
      - name: TF_VAR_RANCHER_PRD_SECRET
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_PRD_SECRET
      - name: TF_VAR_RANCHER_PRD_API_URL
        secretKeyRef:
          name: rancher-credentials
          key: TF_VAR_RANCHER_PRD_API_URL
...
```

We are using the default values for the service account

value | description | default value
-- | -- | --
serviceAccount.create | Whether to create a Kubernetes ServiceAccount if no account matching serviceAccount.name exists. | true
serviceAccount.mount | Whether to mount the Kubernetes ServiceAccount into the pod | true
serviceAccount.name | Name of the Kubernetes ServiceAccount under which Atlantis should run. If no value is specified and serviceAccount.create is true, Atlantis will be run under a ServiceAccount whose name is the FullName of the Helm chart's instance, else Atlantis will be run under the default ServiceAccount. | n/a

The related cluster role binding:

```
atlantis-atlantis-restricted-privileged-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-privileged-clusterrole
subjects:
- kind: ServiceAccount
  name: atlantis
  namespace: atlantis
```

And the cluster role

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-privileged-clusterrole
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - restricted-privileged-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
```

Compared to non-PRD where the deployment works, I added the `""- serviceaccounts- get` to the ClusterRole, but it still does not work
