### ISSUE TITLE
field repo_config_file not found in type raw.Repo

### ISSUE THREAD

**Issue by yiranyao** [runatlantis/helm-charts#275]
I am trying to follow example from https://www.runatlantis.io/docs/server-side-repo-config.html#multiple-atlantis-servers-handle-the-same-repository to setup multiple atlantis servers for the same GitHub repo.

I'm using helm chart version 4.7.0 and atlantis docker container version v0.21.0

My chart value for repoconfig looks something like:
```
repoConfig: |
  ---
  repos:
  - id: "/.*/"
    apply_requirements: [approved]
    delete_source_branch_on_merge: true
    workflow: terragrunt
    repo_config_file: dev.yaml
    ...
```

When I deploy the chart, Atlantis pod crash with error:
│ Error: initializing server: parsing /etc/atlantis/repos.yaml file: yaml: unmarshal errors: 
│   line 7: field repo_config_file not found in type raw.Repo

I've found documents on repo_config_file also at https://www.runatlantis.io/docs/server-side-repo-config.html#repo
I don't understand why atlantis doesn't recognize this field? Please advise. Thanks
