### ISSUE TITLE
Support helm chart for fargate nodes for EKS

### ISSUE THREAD

**Issue by sdwerwed** [runatlantis/helm-charts#40]
Hello, PV need 2 values in addition to work with fargate nodes, I can create PR for updating the helm template if you can give me some direction. 

```
csi:
  driver: efs.csi.aws.com
  volumeHandle: fs-xxxxx
```
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxx
  storageClassName: efs-sc
  volumeMode: Filesystem
  ```
