### ISSUE TITLE
failed to replace pvc object after upgrading from v 4* -> 5*

### ISSUE THREAD

**Issue by j0can** [runatlantis/helm-charts#438]
After following the documentation of: https://github.com/runatlantis/helm-charts/tree/main/charts/atlantis#from-4-to-5

Upgrading to latest version of atlantis helm chart (5.9.1) from version 5.0.0 prompts the following error below:

Error: failed to replace object: PersistentVolumeClaim "atlantis-data" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
│   core.PersistentVolumeClaimSpec{
│ -     VolumeName:       "current volume",
│ +     VolumeName:       "",

With current statefulset and pvc used, the upgrade/template wants to leave volumeName to empty string, as shown above. As i understand that `Forbidden: spec is immutable after creation except resources.requests for bound claims` is a Kubernetes restriction.

Is there any possibility in helm to use exsistingClaim for the volume claim value:
pvc.yml:

```yaml
{{- if .Values.volumeClaim.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeClaim.existingClaim }}
  namespace: {{ .Release.Namespace }}
{{- else }}
```

my current volumeClaim values:
```yaml
volumeClaim:
  dataStorage: 50Gi
```

**Comment by GMartinez-Sisti** [comment]
Hi @j0can, there shouldn't be any issue if your current version is 5.0.0. You can keep using an existing claim with:

https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/values.yaml#L431

Would this fix your issue?

**Comment by j0can** [comment]
Hi @GMartinez-Sisti  
I have it in my values.yaml but it does not keep my existing claim when upgrading.
 ```yaml
volumeClaim:
  dataStorage: 50Gi
 ```

**Comment by GMartinez-Sisti** [comment]
> Hi @GMartinez-Sisti I have it in my values.yaml but it does not keep my existing claim when upgrading.
> 
> ```yaml
> volumeClaim:
>  dataStorage: 50Gi
> ```

Can you please share your entire values file so I can test the migration? We're not supposed to specify the claim name since it should be automatically created.

**Comment by j0can** [comment]
this is how the current values.yaml looks like

```yaml
image:
  repository: 123456781234.dkr.ecr.eu-north-1.amazonaws.com/atlantis-terragrunt
  tag: 0.0.1

orgAllowlist: github.com/myorg/myrepo

vcsSecretName: atlantis-test
basicAuthSecretName: atlantis-basic-auth

githubApp:
  id: 123456
  slug: atlantis-slug

aws:
  config: |
    [profile atlantis-prod]
    role_arn = arn:aws:iam::123456781234:role/atlantis-irsa
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token

ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "${alb_certificate_arn}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: "${alb_group_name}"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
  host: "${alb_internal_fqdn}"
  tls:
    - hosts:
        - "${alb_internal_fqdn}"
      secretName: atlantis-tls
  path: /*
  pathType: ImplementationSpecific

webhook_ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "${alb_certificate_arn}"
    alb.ingress.kubernetes.io/group.name: "external"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/inbound-cidrs:
  host: "${alb_external_fqdn}"
  tls:
    - hosts:
        - "${alb_external_fqdn}"
      secretName: atlantis-webhook-tls

environment:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: 0
  TERRAGRUNT_NON_INTERACTIVE: "true"
  TERRAGRUNT_TFPATH: "terraform"
  TERRAGRUNT_FORWARD_TF_STDOUT: "true"
  ATLANTIS_SILENCE_ALLOWLIST_ERRORS: "true"
  ATLANTIS_AUTODISCOVER_MODE: false
  ATLANTIS_FAIL_ON_PRE_WORKFLOW_HOOK_ERROR: "true"
  ATLANTIS_GH_ALLOW_MERGEABLE_BYPASS_APPLY: "true"
  ATLANTIS_SILENCE_NO_PROJECTS: "true"
  ATLANTIS_AUTOPLAN_FILE_LIST: "disabled"
  ATLANTIS_HIDE_PREV_PLAN_COMMENTS: "true"
  ATLANTIS_HIDE_UNCHANGED_PLAN_COMMENTS: "true"
  ATLANTIS_ALLOW_COMMANDS: "version,plan,apply,unlock,approve_policies,import"
  ATLANTIS_DISABLE_AUTOPLAN_LABEL: "no-autoplan"
  ATLANTIS_ENABLE_DIFF_MARKDOWN_FORMAT: "true"
  ATLANTIS_EMOJI_REACTION: "eyes"

repoConfig: |
  ---
  repos:
  - id: github.com/myorg/myrepo
    branch: /^master$/
    apply_requirements: [approved, mergeable]
    import_requirements: [approved, mergeable]
    workflow: terragrunt
    repo_locking: true
    pre_workflow_hooks:
     - run: |
         [ -d "/home/atlantis/.terraform.d/" ] || mkdir -p "/home/atlantis/.terraform.d/"
         export ALLOWED_PATHS="aws/atlantis/prod/eu-north-1"
         terragrunt-atlantis-generate.sh
         unset ALLOWED_PATHS
    post_workflow_hooks:
     - run: find ../ -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;

  workflows:
   terragrunt:
     plan:
       steps:
       - env:
           name: TERRAGRUNT_TFPATH
           command: 'echo "terraform$$${ATLANTIS_TERRAFORM_VERSION}"'
       - env:
           name: DESTROY_PARAMETER
           command: if [ "$COMMENT_ARGS" = "\-\d\e\s\t\r\o\y" ]; then echo "-destroy"; else echo ""; fi
       - run:
           command: terragrunt plan -no-color -out "$PLANFILE" $DESTROY_PARAMETER
           output: hide
       - run: terragrunt show -no-color "$PLANFILE"
     apply:
       steps:
       - env:
           name: TERRAGRUNT_TFPATH
           command: 'echo "terraform$$${ATLANTIS_TERRAFORM_VERSION}"'
       - run: terragrunt apply -no-color "$PLANFILE"

serviceAccount:
  name: atlantis-irsa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456781234:role/atlantis-irsa

enableDiffMarkdownFormat: true

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 4Gi

volumeClaim:
  dataStorage: 50Gi

```

**Comment by j0can** [comment]
was this tested? any update on this :)

**Comment by j0can** [comment]
hello @GMartinez-Sisti 
after deploying yet another deployment with this helmchart version, i get the same error.

```yml
│ -     VolumeName:       "pvc-id",
│ +     VolumeName:       "",
│ -     StorageClassName: &"default",
│ +     StorageClassName: nil,
```

**Comment by GMartinez-Sisti** [comment]
Hi @j0can,

I tested your configuration and I still can't find the issue you are having.

Using the values file, from your post.
<details>
  <summary>Click to expand result.</summary>
  
  ```sh
→ cat myvalues.yaml
image:
  repository: 123456781234.dkr.ecr.eu-north-1.amazonaws.com/atlantis-terragrunt
  tag: 0.0.1

orgAllowlist: github.com/myorg/myrepo

vcsSecretName: atlantis-test
basicAuthSecretName: atlantis-basic-auth

githubApp:
  id: 123456
  slug: atlantis-slug

aws:
  config: |
    [profile atlantis-prod]
    role_arn = arn:aws:iam::123456781234:role/atlantis-irsa
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token

ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "${alb_certificate_arn}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: "${alb_group_name}"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
  host: "${alb_internal_fqdn}"
  tls:
    - hosts:
        - "${alb_internal_fqdn}"
      secretName: atlantis-tls
  path: /*
  pathType: ImplementationSpecific

webhook_ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: "${alb_certificate_arn}"
    alb.ingress.kubernetes.io/group.name: "external"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    #alb.ingress.kubernetes.io/inbound-cidrs:
  host: "${alb_external_fqdn}"
  tls:
    - hosts:
        - "${alb_external_fqdn}"
      secretName: atlantis-webhook-tls

environment:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: 0
  TERRAGRUNT_NON_INTERACTIVE: "true"
  TERRAGRUNT_TFPATH: "terraform"
  TERRAGRUNT_FORWARD_TF_STDOUT: "true"
  ATLANTIS_SILENCE_ALLOWLIST_ERRORS: "true"
  ATLANTIS_AUTODISCOVER_MODE: false
  ATLANTIS_FAIL_ON_PRE_WORKFLOW_HOOK_ERROR: "true"
  ATLANTIS_GH_ALLOW_MERGEABLE_BYPASS_APPLY: "true"
  ATLANTIS_SILENCE_NO_PROJECTS: "true"
  ATLANTIS_AUTOPLAN_FILE_LIST: "disabled"
  ATLANTIS_HIDE_PREV_PLAN_COMMENTS: "true"
  ATLANTIS_HIDE_UNCHANGED_PLAN_COMMENTS: "true"
  ATLANTIS_ALLOW_COMMANDS: "version,plan,apply,unlock,approve_policies,import"
  ATLANTIS_DISABLE_AUTOPLAN_LABEL: "no-autoplan"
  ATLANTIS_ENABLE_DIFF_MARKDOWN_FORMAT: "true"
  ATLANTIS_EMOJI_REACTION: "eyes"

repoConfig: |
  ---
  repos:
  - id: github.com/myorg/myrepo
    branch: /^master$/
    apply_requirements: [approved, mergeable]
    import_requirements: [approved, mergeable]
    workflow: terragrunt
    repo_locking: true
    pre_workflow_hooks:
     - run: |
         [ -d "/home/atlantis/.terraform.d/" ] || mkdir -p "/home/atlantis/.terraform.d/"
         export ALLOWED_PATHS="aws/atlantis/prod/eu-north-1"
         terragrunt-atlantis-generate.sh
         unset ALLOWED_PATHS
    post_workflow_hooks:
     - run: find ../ -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;

  workflows:
   terragrunt:
     plan:
       steps:
       - env:
           name: TERRAGRUNT_TFPATH
           command: 'echo "terraform$$${ATLANTIS_TERRAFORM_VERSION}"'
       - env:
           name: DESTROY_PARAMETER
           command: if [ "$COMMENT_ARGS" = "\-\d\e\s\t\r\o\y" ]; then echo "-destroy"; else echo ""; fi
       - run:
           command: terragrunt plan -no-color -out "$PLANFILE" $DESTROY_PARAMETER
           output: hide
       - run: terragrunt show -no-color "$PLANFILE"
     apply:
       steps:
       - env:
           name: TERRAGRUNT_TFPATH
           command: 'echo "terraform$$${ATLANTIS_TERRAFORM_VERSION}"'
       - run: terragrunt apply -no-color "$PLANFILE"

serviceAccount:
  name: atlantis-irsa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456781234:role/atlantis-irsa

enableDiffMarkdownFormat: true

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 4Gi

volumeClaim:
  dataStorage: 50Gi
  ```

</details>

Getting the templates and running a diff:

```sh
helm template runatlantis/atlantis --version 5.0.0 -f myvalues.yaml > atlantis-5-0-0.yaml
helm template runatlantis/atlantis --version 5.11.0 -f myvalues.yaml > atlantis-5-11-0.yaml
diff atlantis-5-0-0.yaml atlantis-5-11-0.yaml
```

This is what I get:

```diff
6a7
>   namespace: default
9,10c10,11
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
20a22
>   namespace: default
23,24c25,26
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
34a37
>   namespace: default
37,38c40,41
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
85a89
>   namespace: default
101a106
>   namespace: default
104,105c109,110
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
121a127
>   namespace: default
124,125c130,131
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
143a150
>   namespace: default
146,147c153,154
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
164c171
<         checksum/repo-config: 159491cce01dd1fa2c053b13cdcf7905acd07748a2e821881d9084a379361107
---
>         checksum/repo-config: 253cdfe96d8914db282e1e97cc46a67c50c998fdcaf34f31f6e68d6af00a9a1d
199a207,208
>           - name: PATH
>             value: /plugins:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
235a245,246
>           - name: ATLANTIS_TF_DISTRIBUTION
>             value: terraform
315a327
>   namespace: default
318,319c330,331
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
352a365
>   namespace: default
355,356c368,369
<     chart: atlantis-5.0.0
<     helm.sh/chart: atlantis-5.0.0
---
>     chart: atlantis-5.11.0
>     helm.sh/chart: atlantis-5.11.0
388a402
>   namespace: default
```

Double checking that they are the same:

```sh
→ yq '. | select(.kind == "PersistentVolumeClaim")' atlantis-5-0-0.yaml
```
```yaml
# Source: atlantis/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-atlantis-data
  labels:
    app: atlantis
    chart: atlantis-5.0.0
    helm.sh/chart: atlantis-5.0.0
    release: release-name
    heritage: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The biggest thing Atlantis stores is the Git repo when it checks it out.
      # It deletes the repo after the pull request is merged.
      storage: 50Gi
```

```sh
→ yq '. | select(.kind == "PersistentVolumeClaim")' atlantis-5-11-0.yaml
```
```yaml
# Source: atlantis/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-atlantis-data
  namespace: default
  labels:
    app: atlantis
    chart: atlantis-5.11.0
    helm.sh/chart: atlantis-5.11.0
    release: release-name
    heritage: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The biggest thing Atlantis stores is the Git repo when it checks it out.
      # It deletes the repo after the pull request is merged.
      storage: 50Gi
```

I can only assume your values are not being passed correctly?
