### ISSUE TITLE
Atlantis.yaml is not found and auto-planning is failing

### ISSUE THREAD

**Issue by yashaswee** [runatlantis/helm-charts#44]
In our atlantis set-up I can see the atlantis.yaml and repo.yaml mounted on the pod:
```
Mounts: /atlantis-data from atlantis-data (rw) /etc/atlantis/atlantis.yaml from config (ro,path="atlantis.yaml") /etc/atlantis/repos.yaml from repo-config (ro,path="repos.yaml")
Args: server --config=/etc/atlantis/atlantis.yaml
```

In my local setup I did exec in the pod and I could see the file atlantis.yaml.

In the logs though it is saying :
`Mar 24 12:56:12 k8s-pipeline-atlantis-0 atlantis 2021/03/24 17:56:12+0000 [INFO] server: Executing autoplan Mar 24 12:56:13 k8s-pipeline-atlantis-0 atlantis 2021/03/24 17:56:12+0000 [INFO] XXX/YYY#728: Found no atlantis.yaml file`

We are trying not to run auto-plan for all the folders in a project but only for a single folder. We defined our custom plan in repo.yaml and allowed override for `apply_requirements, workflow` and it looks like:
`
```
repoConfig: |
          ---
          repos:
            - id: /.*/
              apply_requirements: [approved, mergeable]
              workflow: default
              allowed_overrides: [apply_requirements, workflow]
              allow_custom_workflows: true
          workflows:
            default:
              plan:
                steps:
                  - run: terraform$ATLANTIS_DEFAULT_TF_VERSION init -input=false -lock=false
                  - run: terraform$ATLANTIS_DEFAULT_TF_VERSION plan -input=false -refresh -no-color -lock=false
              apply:
                steps:
                  - run: terraform$ATLANTIS_DEFAULT_TF_VERSION apply -auto-approve -no-color -lock=false
````
`
```yaml
config: |
          version: 3
          gitlab-hostname: https://gitlab.XXX.com
          projects:
            - dir: test-org
              workspace: default
              terraform_version: v0.12.30
              autoplan:
                when_modified: ["**.tf"]
                enabled: true
              apply_requirements: [mergeable, approved]
              workflow: default
            - dir: .
              autoplan:
                enabled: false
            - dir: infra
              autoplan:
                enabled: false
```
 We moved the workflows now in atlantis.yaml.
We defined auto-run as false for other folders in atlantis.yaml but based on the logs, atlantis can not locate this file.

Any idea what might be wrong in our settings?
