### ISSUE TITLE
WARNING: Flag --tf-distribution has been deprecated

### ISSUE THREAD

**Issue by den-is** [runatlantis/helm-charts#453]
Saw this warning after upgrade to 0.33.0. Helm chart 5.13.0

> WARNING: Flag --tf-distribution has been deprecated.

Tryed to apply a temporary workaround, until someone fixes it in the helm chart.

Values:
```yaml
defaultTFDistribution: ""
environment:
  ATLANTIS_DEFAULT_TF_DISTRIBUTION: terraform
```

But "unfortunately", I got helm upgrade error:
```
> Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
atlantis:
- defaultTFDistribution: defaultTFDistribution must be one of the following: "terraform", "opentofu"
