### ISSUE TITLE
Does the helm chart support gitlab instances running on ports other than 443/https?

### ISSUE THREAD

**Issue by RoFz** [runatlantis/helm-charts#460]
I'd like to set up Atlantis as a pod on the same cluster where our gitlab instance runs on. It happens that, by default and without TLS, the gitlab workhorse service listens on port 8181. This leads Atlantis' deployment to fail with the error below, since it apparently wants to connect to gitlab using port 443:

```
Defaulted container "atlantis" out of: atlantis, init-gitlab-runner-certs (init)
No files found in /docker-entrypoint.d/, skipping
WARNING: Flag --tf-distribution has been deprecated.
Error: initializing server: Get "https://gitlab-webservice-default.gitlab/api/v4/version": dial tcp 10.104.93.219:443: i/o timeout

```

Gitlab webservice service:

```
NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                               AGE
...
gitlab-webservice-default   ClusterIP   10.104.93.219    <none>        8080/TCP,8181/TCP,8083/TCP            17
```

Atlantis values.yaml:

```yaml
    orgAllowlist: gitlab-webservice-default.gitlab/*
    logLevel: info
    gitlab:
      user: rofz
      token: glpat-<token>
      secret: <random_secret>
      hostname: gitlab-webservice-default.gitlab
```

Is it possible to tell Atlantis via its helm chart that Gitlab is in another port? Also, is it possible to use http instead of https?

Secondarily, could you clarify why the _values.yaml_ file has the comment below, please? I understand that without the `hostname` key it would **not** be possible to have Atlantis to connect to our local Gitlab CE since it will target the default https://gitlab.com, is that correct?

`# The 'hostname' key is exclusive to GitLab Enterprise installations.`
