### ISSUE TITLE
Wrong type comparison for containerPort

### ISSUE THREAD

**Issue by Lynggaard91** [runatlantis/helm-charts#471]
Hello! 

~~There's an issue with the helm chart 5.7.2.~~

I experience a weird issue where others don't apparently, so I'm uncertain if this is a 'does not work on my machine' situation, as my colleague manages to template the chart just fine.

```
$ version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

### Issue
All references to the definition [`atlantis.containerPort`](https://github.com/runatlantis/helm-charts/blob/efc6eaa8f39a02d3df0debabac48bef83bb1317d/charts/atlantis/templates/_helpers.tpl#L148) in _helpers.tpl will erroneously use port 0 because the `default` function _likely_ evaluates [`.Values.containerPort`](https://github.com/runatlantis/helm-charts/blob/efc6eaa8f39a02d3df0debabac48bef83bb1317d/charts/atlantis/values.yaml#L176) as a string.

I do not use a values.yaml file but template directly based on a local clone of this repository.

```yaml
---
# Source: atlantis/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-atlantis
  ...
      containers:
        - name: atlantis
        ...
          ports:
          - name: atlantis
            containerPort: 0
          env:
          ...
          - name: ATLANTIS_PORT
            value: "0"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 0
              scheme: HTTP
            ...
          readinessProbe:
            httpGet:
              path: /healthz
              port: 0
              scheme: HTTP
            ...
---
```

### 'Fix'

Type conversion of `Values.containerPort` to an `int` evaluates to the expected value as per comment [here](https://github.com/runatlantis/helm-charts/blob/efc6eaa8f39a02d3df0debabac48bef83bb1317d/charts/atlantis/values.yaml#L175)

```tpl
{{/*
Sets the container port based on the defined values.
*/}}
{{- define "atlantis.containerPort" -}}
{{- default .Values.service.targetPort (int .Values.containerPort)  }}
{{- end -}}
```

```yaml
---
# Source: atlantis/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-atlantis
  ...
      containers:
        - name: atlantis
          ...
          ports:
          - name: atlantis
            containerPort: 4141
          env:
          ...
          - name: ATLANTIS_PORT
            value: "4141"
          ...
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
            ...
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
            ...
---
```

**Comment by GMartinez-Sisti** [comment]
Hi @Lynggaard91, thanks for reporting this.

I confirmed that this works correctly with:

```sh
→ helm version
version.BuildInfo{Version:"v3.17.3", GitCommit:"e4da49785aa6e6ee2b86efd5dd9e43400318262b", GitTreeState:"clean", GoVersion:"go1.24.2"}
```

```yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4141
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
```

Then I noticed you are using the latest helm version and I updated to the latest:

```sh
→ helm version
version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

Which indeed results in:

```yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 0
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 0
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
```

Looks like the behavior change might've caused by https://github.com/helm/helm/pull/13534, which was already reverted in https://github.com/helm/helm/issues/30901 and also reported in https://github.com/helm/helm/issues/30880 but it got into helm 3.18, a fix should be available in the next helm version.

Let's wait for the fix to drop and then we can see if we can still introduce your suggested fix.

Thanks!
