### ISSUE TITLE
line 8: field policies not found in type raw.GlobalCfg     

### ISSUE THREAD

**Issue by worldwideward** [runatlantis/helm-charts#49]
I'm using the Atlantis Helm Chart with server side repo config, trying to get polciy checks to work.

```yaml
# values.yaml
repoConfig: |
  ---
  repos:
  - id: /.*/
    apply_requirements: [policy checking, mergeable]
    workflow: default
    allowed_overrides: []
    allow_custom_workflows: false
  policies:
    owners:
      users:
        - user
    policy_sets:
      - name: main
        path: /policies
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
```
I sort of copy pasted the example from the official docs ( https://www.runatlantis.io/docs/policy-checking.html#step-3-define-the-policy-configuration)

but when I  upgrade the helm chart I get an error from my atlantis server:

```bash
Error: initializing server: parsing /etc/atlantis/repos.yaml file: yaml: unmarshal errors:                                                                                                                      
line 8: field policies not found in type raw.GlobalCfg         
```

I assume my syntax is right (still I could be wrong) , so either the Helm chart doesn't support polices yet or?

Many thanks for the help already!
